# Tri_classa_isklychenii_unasledovannih_ot_BaseException
3 класса исключений унаследованных от BaseException
Дано задание: (без вариантов)
Создать 3 класса исключений унаследованных от BaseException
После просмотра кода можно сделать небольшие выводы:
Для каждого из трех классов исключений задано свое сообщение об ошибке.
И функция test_function возбуждает одно из этих исключений в зависимости от переданного ей аргумента.
